---
_hotel_id: TTDEMO
_portal_id: demo
latitude: 40.7507385
longitude: -73.97681210000002
name: Paradise Hotel
email: allsystememails@traveltripper.com
phone_number: 1-212-683-6161
address:
  street1: 370 Lexington Avenue
  street2: Suite 1601
  state: New York
  city: New York
  country: United States
  zip_code: '10017'
